default:
	@echo "Please select a target"

oregon-b:
	python3 -m meaoelb.bedrock_oregon_b
	python3 -m meaoelb.careers_oregon_b
	python3 -m meaoelb.snippets_oregon_b
	python3 -m meaoelb.sumo_oregon_b

apply-oregon-b:
	python3 -m meaoelb.bedrock_oregon_b --apply
	python3 -m meaoelb.careers_oregon_b --apply
	python3 -m meaoelb.snippets_oregon_b --apply
	python3 -m meaoelb.sumo_oregon_b --apply

bedrock-oregon-b:
	python3 -m meaoelb.bedrock_oregon_b

apply-bedrock-oregon-b:
	python3 -m meaoelb.bedrock_oregon_b --apply

careers-oregon-b:
	python3 -m meaoelb.careers_oregon_b

apply-careers-oregon-b:
	python3 -m meaoelb.careers_oregon_b --apply

snippets-oregon-b:
	python3 -m meaoelb.snippets_oregon_b

apply-snippets-oregon-b:
	python3 -m meaoelb.snippets_oregon_b --apply

sumo-oregon-b:
	python3 -m meaoelb.sumo_oregon_b

apply-sumo-oregon-b:
	python3 -m meaoelb.sumo_oregon_b --apply

ap-northeast-1:
	python3 -m meaoelb.ap_northeast_1

eu-central-1:
	python3 -m meaoelb.eu_central_1

