default:
	@echo "Please select a target"

oregon-b:
	# you MUST specify --apply at the end of this command to 
	# actually perform the changes
	python3 -m meaoelb.oregon_b

ap-northeast-1:
	python3 -m meaoelb.ap_northeast_1

eu-central-1:
	python3 -m meaoelb.eu_central_1

