name: Mirror repo
on: [push]

jobs:
  mirror:
    if: github.repository == 'mozmeao/infra'
    runs-on: ubuntu-latest
    steps:
       - name: mirror in gitlab
         uses: actions/checkout@v3
         with:
          fetch-depth: 0
       - uses: yesolutions/mirror-action@master
         with:
            REMOTE: 'https://gitlab.com/mozmeao/infra.git'
            GIT_USERNAME: ${{ secrets.GITLAB_USERNAME }}
            GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
